#!/usr/bin/env bash
# Generates .env for production from environment variables (GitHub Actions secrets).
set -euo pipefail

cat <<EOF
PORT=${PORT:-8080}
DATABASE_URL=${DATABASE_URL:-jdbc:sqlite:/data/kkalscan.db}

JWT_SECRET=${JWT_SECRET:?JWT_SECRET is required}
JWT_ISSUER=${JWT_ISSUER:-kkalscan}
JWT_TTL_SECONDS=${JWT_TTL_SECONDS:-2592000}

VISION_PROVIDER=${VISION_PROVIDER:-stub}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.0-flash-001}
OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
OPENROUTER_APP_URL=${OPENROUTER_APP_URL:-http://91.207.75.72:8080}
OPENROUTER_APP_NAME=${OPENROUTER_APP_NAME:-KkalScan}
VISION_MONTHLY_BUDGET_RUB=${VISION_MONTHLY_BUDGET_RUB:-5000}
VISION_COST_PER_REQUEST_RUB=${VISION_COST_PER_REQUEST_RUB:-1}

TOCHKA_MERCHANT_ID=${TOCHKA_MERCHANT_ID:-}
TOCHKA_SECRET_KEY=${TOCHKA_SECRET_KEY:-}
TOCHKA_WEBHOOK_SECRET=${TOCHKA_WEBHOOK_SECRET:-}

VK_APP_ID=${VK_APP_ID:-}
VK_SERVICE_TOKEN=${VK_SERVICE_TOKEN:-}
EOF
