#!/usr/bin/env bash
# Generates .env for production from environment variables (GitHub Actions secrets).
set -euo pipefail

cat <<EOF
PORT=${PORT:-8080}
DATABASE_URL=${DATABASE_URL:-jdbc:sqlite:/data/kkalscan.db}

JWT_SECRET=${JWT_SECRET:?JWT_SECRET is required}
JWT_ISSUER=${JWT_ISSUER:-kkalscan}
JWT_TTL_SECONDS=${JWT_TTL_SECONDS:-2592000}

# Vision: always stub in deploy (change here when switching to OpenRouter).
VISION_PROVIDER=stub
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.5-flash}
OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
OPENROUTER_APP_URL=${OPENROUTER_APP_URL:-http://91.207.75.72:8080}
OPENROUTER_APP_NAME=${OPENROUTER_APP_NAME:-KkalScan}
VISION_MONTHLY_BUDGET_RUB=${VISION_MONTHLY_BUDGET_RUB:-5000}
VISION_COST_PER_REQUEST_RUB=${VISION_COST_PER_REQUEST_RUB:-1}

SMTP_HOST=${SMTP_HOST:-mail.antonbutov.com}
SMTP_PORT=${SMTP_PORT:-465}
SMTP_USER=${SMTP_USER:-mail@antonbutov.com}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_FROM=${SMTP_FROM:-mail@antonbutov.com}
BUG_REPORT_NOTIFY_TO=${BUG_REPORT_NOTIFY_TO:-mail@antonbutov.com}
SMTP_USE_TLS=${SMTP_USE_TLS:-true}

TOCHKA_MERCHANT_ID=${TOCHKA_MERCHANT_ID:-}
TOCHKA_SECRET_KEY=${TOCHKA_SECRET_KEY:-}
TOCHKA_ACCESS_TOKEN=${TOCHKA_ACCESS_TOKEN:-}
TOCHKA_CUSTOMER_CODE=${TOCHKA_CUSTOMER_CODE:-}
TOCHKA_WEBHOOK_SECRET=${TOCHKA_WEBHOOK_SECRET:-}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://91.207.75.72:8080}

VK_APP_ID=${VK_APP_ID:-}
VK_SERVICE_TOKEN=${VK_SERVICE_TOKEN:-}
EOF
