#!/usr/bin/env bash
# Generates .env for production from environment variables (GitHub Actions secrets).
# Usage: export JWT_SECRET=... GEMINI_API_KEY=... && ./scripts/generate-env.sh > .env
set -euo pipefail

cat <<EOF
PORT=${PORT:-8080}
DATABASE_URL=${DATABASE_URL:-jdbc:sqlite:/data/kkalscan.db}

JWT_SECRET=${JWT_SECRET:?JWT_SECRET is required}
JWT_ISSUER=${JWT_ISSUER:-kkalscan}
JWT_TTL_SECONDS=${JWT_TTL_SECONDS:-2592000}

VISION_PROVIDER=${VISION_PROVIDER:-stub}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
VISION_MONTHLY_BUDGET_RUB=${VISION_MONTHLY_BUDGET_RUB:-5000}
VISION_COST_PER_REQUEST_RUB=${VISION_COST_PER_REQUEST_RUB:-1}

TOCHKA_MERCHANT_ID=${TOCHKA_MERCHANT_ID:-}
TOCHKA_SECRET_KEY=${TOCHKA_SECRET_KEY:-}
TOCHKA_WEBHOOK_SECRET=${TOCHKA_WEBHOOK_SECRET:-}

VK_APP_ID=${VK_APP_ID:-}
VK_SERVICE_TOKEN=${VK_SERVICE_TOKEN:-}
EOF
